[project]
name = "aoc24"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "networkx>=3.4.2",
    "numpy>=2.1.3",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
